version: '3.4'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v4.12.0
    environment:
        - URL=/api.yaml 
    volumes:
        - ./api.yaml:/usr/share/nginx/html/api.yaml  
    ports:
        - 80:8080

  db:
    image: mariadb:10
    ports: 
        - 3306:3306
    environment:
        - MARIADB_ROOT_PASSWORD=secret1234
        - MARIADB_DATABASE=hellodb
        - MARIADB_USER=hellouser
        - MARIADB_PASSWORD=secret1234

  
  kitnugs:
    image: ${DOCKER_REGISTRY-}kitnugs
    build:
      context: .
      dockerfile: KitNugs/Dockerfile
    environment: 
        - TEST_VAR=TEST VARIABLE
        - "Serilog__MinimumLevel__Default=Debug"
        - "ConnectionStrings__db=server=db;user=hellouser;password=secret1234;database=hellodb"
    ports:
        - "8090:8080"
        - "8091:8081"
