version: '3.4'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v4.12.0
    environment:
        - URL=/api.yaml 
    volumes:
        - ./api.yaml:/usr/share/nginx/html/api.yaml  
    ports:
        - 80:8080

  db:
    image: mariadb:10
    environment:
        - MARIADB_ROOT_PASSWORD=secret1234
        - MARIADB_DATABASE=hellodb
        - MARIADB_USER=hellouser
        - MARIADB_PASSWORD=secret1234

  
  kitnugs:
    image: ${DOCKER_REGISTRY-}kitnugs
    build:
      context: .
      dockerfile: KitNugs/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
